services:
  - type: web
    name: djangorest # Elige un nombre para tu servicio
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn restframework.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mi-basededatos # El nombre de tu base de datos
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4

databases:
  - name: mi-basededatos # Elige un nombre para tu base de datos
    databaseName: mi_base_de_datos # Nombre interno de la base de datos
    user: usuario_db # Nombre de usuario para la base de datos
    plan: free # Puedes elegir un plan de pago para mayor rendimiento
